language: node_js
node_js:
  - "7"

cache: 
  directories:
    - node_modules

install:
    - npm install gitlog --save
    - npm install file-system --save
    - npm install jest --save
    - npm install 

script:
    - ./deploy.sh